services:
  - type: worker
    name: habit-tracker-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TZ
        value: Asia/Aqtobe
